server:
  port: 8082

spring:
  datasource:                                   # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect
    password: 123456

# mybatis配置
mybatis:

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # StdOutImpl表示的是控制台的实现