server:
  #  port: 8082
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

spring:
  profiles:
    active: prod
  datasource:                                   # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource    # 数据源类型，HikariCP
    driver-class-name: com.mysql.jdbc.Driver    # mysql 驱动
    #url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect
    username: root
    #password: 123456
    hikari:
      connection-timeout: 30000 # 等待
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 512000 # 文件上传大小为500kb
      max-request-size:  512000  # 请求大小限制为500kb

# mybatis配置
mybatis:
  type-aliases-package: com.imooc.pojo
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # StdOutImpl表示的是控制台的实现


# 内置tomcat的配置


## Mybatis Mapper配置
mapper:
  mappers: com.imooc.my.mapper.MyMapper
  not-empty: false # 在进行数据库操作时，判断表达式username != null, 是否追加 username != "
  identity: MYSQL

# 分页插件配置
#    pagehelper:
#
pagehelper:
  helperDialect: mysql
  support-methods-arguments: true
#      supportMethodsArguments: true